const MessageTypes = require('./MessageTypes');


class MessageClassifier {
  classifyMessage (message) {
    if (this._isMailServer(message)) {
      return MessageTypes.MAIL_SERVER;
    }

    if (this._isAutoresponder(message)) {
      return MessageTypes.AUTORESPONDER;
    }

    return MessageTypes.HUMAN;
  }

  _isAutoresponder (message) {
    const autoSubmittedValue = message.headers.get('auto-submitted');
    const isAutoSubmitted = !(autoSubmittedValue === undefined || autoSubmittedValue === 'no');

    const xAutoreply = message.headers.get('x-autoreply');
    const hasXAutoreply = xAutoreply && xAutoreply.toLowerCase() === 'yes';

    const xAutogenerated = message.headers.get('x-autogenerated');
    const hasXAutogenerated = xAutogenerated && xAutogenerated.toLowerCase() === 'reply';
    if (isAutoSubmitted || hasXAutoreply || hasXAutogenerated) {
      return true;
    }

    if (message.headers.get('subject').toLowerCase().indexOf('autoreply') !== -1) {
      return true;
    }

    return false;
  }

  _isMailServer (message) {
    const contentType = message.headers.get('content-type');
    if (contentType && typeof contentType.value === 'string' &&
        contentType.value.trim() === 'multipart/report') {
      return true;
    }

    if (message.headers.has('x-mailer-daemon-error') ||
        message.headers.has('x-failed-recipients') ||
        message.headers.has('x-mailer-daemon-recipients')) {
      return true;
    }

    return false;
  }
}

module.exports = MessageClassifier;
